name = "baidaohui-pages"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./public"

[env.production]
name = "baidaohui-pages"

[env.staging]
name = "baidaohui-pages-staging"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your-staging-kv-namespace-id"

[vars]
NODE_ENV = "production"

# 环境变量（在Cloudflare Dashboard中设置）
# SUPABASE_JWT_SECRET
# SESSION_JWT_SECRET  
# MONGODB_URI
# NEXT_PUBLIC_APP_URL 