name = "baidaohui5-pages"
compatibility_date = "2025-04-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./public"

[env.production]
name = "baidaohui5-pages"

# KV namespace configuration - uncomment and set real ID when needed
# [[env.production.kv_namespaces]]
# binding = "CACHE"
# id = "your-real-kv-namespace-id"

[vars]
NODE_ENV = "production"

# 环境变量（在Cloudflare Dashboard中设置）
# SUPABASE_JWT_SECRET
# SESSION_JWT_SECRET  
# MONGODB_URI
# NEXT_PUBLIC_APP_URL 